#docker/Dockerfile.test
FROM mcr.microsoft.com/playwright/python:v1.44.0-jammy

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

# Default to running all tests with allure reporting
CMD ["pytest", "tests/", "-v", "--alluredir=report/allure-results"]